### PR TITLE
Fix invalid Target Temperature

### LINKED ISSUE #9: Floor Heating ºC / ºF Problem
All information appears correctly with the exception of the temperature set for floor heating which appears in ºF regardless of the seal being in ºC.

Outside temperature is not available...

**Logs:**

Show the Homebridge logs here, remove any sensitive information.[24/04/2024, 16:16:29] [PanasonicHeatPumpHomebridgePlugin] Authenticated to Aquarea Smart Panasonic
[24/04/2024, 16:16:30] [PanasonicHeatPumpHomebridgePlugin] Restoring existing accessory from cache: ***
[24/04/2024, 16:16:30] [PanasonicHeatPumpHomebridgePlugin] Restoring existing accessory from cache: ***

**json**

 "email": "xxx",
            "password": "xxx",
            "enableOutdoorTempSensor": true,
            "enableEcoModeSwitch": true,
            "enableComfortModeSwitch": true,
            "refreshTime": 5,
            "platform": "PanasonicHeatPumpHomebridgePlugin"

**Screenshots:**

HK_screen

AQ_screen

**Environment:**

* **Plugin Version**: v2.0.2
* **Homebridge Version**: v1.8.0
* **Node.js Version**: v20.12.2
* **NPM Version**: 10.5.0
* **Operating System**: Docker

### PR DESCRIPTION
**Pull request by pjuszkiewcz**
There are at least two reports that show the adding current temperature to target temperature is not needed nor wanted.  I think that it is because of invalid interpretation of adjustment that you can set when heatpump is using heat curve. Then targetTemp is between -5 and +5 but it doesn't mean it is currentTemp+adjustment. Actually it is f(outsideTemp)+adjustment where f(t) is the heating curve. I think even if I use heat curve (which I do in the winter) I'd like to see the adjustment I set (from -5 to +5) instead of virtual number based on current water temperature.
fixes #9

### CODE REVIEW

**Comment by pjuszkiewcz** [comment]
fixes #9

**Comment by pjuszkiewcz** [comment]
I think it might not work when using weather compensation and target between -5C and 5C and current temperature like 27C. I see that Google Home displays both on the same scale and that will not work (current water temperature is outside the range). I believe for compensation adjustment we should use another characteristic, not TargetTemperature...
But I don't know which one, and I cannot test it in summer...

**Comment by bimusiek** [comment]
Hey @pjuszkiewcz 
Thank you a lot for you contribution.
The problem is that some heat pumps are working using non-linear temperature adjustments (like mine), where you can only set temperature between -5 and +5. Basically moving the delta of heating/cooling power.

That's why there is check for `this.zoneSensor`, to make sure it works for both cases. 
Can you tell me what is the `this.zoneSensor` value in your case?

**Comment by bimusiek** [comment]
HomeKit does not allow negative temps in the thermostat device, this this solution with reading current temp was devised. 
Looking at another project, I think better way would be to take the minimum temp (so in my case -5) and then adjusting all readings by this. So in my case HomeKit could read (0 - 10) when setting temps and then normal temp reading for current temp.

If you wish to improve the PR on these comments, I am happy to merge!

**Comment by pjuszkiewcz** [comment]
Hi,
in the meantime, I changed my mind, because homebridge-gsh has really small support of sensors and also this plugin has recently been archived by the owner, I couldn't implement routine in google home that turns on tank heating when produced power from inverter is enough to cover higher consumption of heat pump. So yesterday and today I implemented reading data from inverter (I'm not using cloud for that as inverter shares this data secured only by basic authentication) and logging into aquarea cloud. The only left is to implement tank control and I should be able to implement this routine inside my own house control application.

Maybe I will come back later, as using Gemini to control lights and asking for the tank water temperature is really nice, but the latter might be not interesting anymore when tank will be heated not only during cheap hours.

However, I'm glad that my poor contribution gave you a kick to fix that issue :) I'm not a TS developer, mainly Java so I don't know if I could manage to do what you asked :)

When I have a time, I'll definitely check your new version.

**Comment by bimusiek** [comment]
I would recommend homeassistant then. I have switched recently from Homebridge and it is much better.

**Pull request closed without merging**
